language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: gjMZoZaL6BI8YpD881+4BTltZAyfIQyrl8EBtWfifkLdS5VFQkOx9NBA+qN6Snrmt9oDemYVYwe5HsHB7syQ50NOSQsdYNglqVIwFmDBJEanbjAHskmkAD09XlfOZRSd6WhdCQfMdsYKLebO3AG2dLZ5QIlvh1IzTWxMy4EOTI95/D8lDKF397Yg2eGPYX78a4tKLNyRSXLvwQlWACn2dC+EMDNxlH9de4KcthJX2jTtRJ2bPytMVeseox/8QFpaY/lCtpiPTFp8ZlLqzfgKdOZ8SKm/zthF/HKFrPs7raBaL2j0hsz3IfeBEbGcdbNRTVpYcvwaw/7iWceOBtBhyAy3neDe1vPCWCaMyb4XDOjRmGB/Wg2mAx5MGaDT6OEdxPhPGocv4SElyIzjzFONsofQM3FQ+GoU/UtKKCjgGQ8s3BxCGxNY891G6rjL5cC4/5SCBrfFn0P3mE1ldn7K1P07hiAOE5/pcwZvAm7JADZTGsijIwEZXoeVbkG6k1vyqYG/S+N0tIzxUrt5khYkqN1Dj8pfyScbfg4q6yy78cGSPAF7f1Gggc0PjJ6skLuwvH+XNNjXSIm/qaxopDkK5Hu8dwCCAqdVRiW3Ol2B+jJQt755s+w1FTUvK/Oc34Qt6XtQartUY/B3OSHmehRIeB3c4gfA6Yjwt1KhLSQxoBE=
  app: viewing-party-2103
  run: rails db:migrate
